spring:
  profiles:
    active: chenjk

#dubbo:
#  application: 
#    name: dubbo-consumer-demo
#  consumer:
#    timeout: 30000
#  registry: 
#    address: zookeeper://XXX:2181
#server: 
#  port: 9001
##  context-path: /app
#spring:
#  kafka:
#    consumer:
#      enable-auto-commit: true #指定消息被消费之后自动提交偏移量（即消息的编号，
##表示消费到了哪个位置，消费者每消费完一条消息就会向kafka服务器汇报自己消消费到的那个消息的编号，
##以便于下次继续消费）。
#      group-id: applog  #消费者组
#      auto-offset-reset: latest  #从最近的地方开始消费
#      bootstrap-servers: XXX:9092
  